//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationColorsMapping
    {
        public int Id { get; set; }
        public Nullable<int> PrintColor_Id { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblApplicationProcess tblApplicationProcess { get; set; }
        public virtual tblPrintColor tblPrintColor { get; set; }
    }
}
