//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApplicationColour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblApplicationColour()
        {
            this.TblApplicationColoursMappings = new HashSet<TblApplicationColoursMapping>();
        }
    
        public int ApplicationColourId { get; set; }
        public Nullable<int> ColourWayNo { get; set; }
        public Nullable<int> InkId { get; set; }
        public string InkColour { get; set; }
        public Nullable<int> ThreadId { get; set; }
        public string ThreadColour { get; set; }
        public Nullable<int> Pantone { get; set; }
        public Nullable<int> PrintOrder { get; set; }
        public string Mesh { get; set; }
        public Nullable<bool> Flash { get; set; }
        public string TransferColour { get; set; }
        public string Substrate { get; set; }
        public string ColourNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string GarmentColour { get; set; }
    
        public virtual tblPantoneMaster tblPantoneMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblApplicationColoursMapping> TblApplicationColoursMappings { get; set; }
    }
}
