//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblApplication()
        {
            this.tblApplicationCustomInfoMappings = new HashSet<tblApplicationCustomInfoMapping>();
            this.TblApplicationColoursMappings = new HashSet<TblApplicationColoursMapping>();
            this.tbloptions = new HashSet<tbloption>();
            this.tbloptions1 = new HashSet<tbloption>();
            this.tbloptions2 = new HashSet<tbloption>();
            this.tbloptions3 = new HashSet<tbloption>();
            this.tbloptions4 = new HashSet<tbloption>();
        }
    
        public int ApplicationId { get; set; }
        public string AppName { get; set; }
        public Nullable<System.DateTime> DecorationDate { get; set; }
        public string AppType { get; set; }
        public string AppWidth { get; set; }
        public string Art { get; set; }
        public string ArtNotes { get; set; }
        public string Bill { get; set; }
        public string Production { get; set; }
        public string ProductionNotes { get; set; }
        public string ArtSupplier { get; set; }
        public string Designer { get; set; }
        public string DesignerNotes { get; set; }
        public string AppStatus { get; set; }
        public string ProofNotes { get; set; }
        public Nullable<int> AcctMgrId { get; set; }
        public string AppImage { get; set; }
        public string AppVector { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string SourceImage { get; set; }
        public string Link { get; set; }
        public string MockUpImage { get; set; }
    
        public virtual tbluser tbluser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationCustomInfoMapping> tblApplicationCustomInfoMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblApplicationColoursMapping> TblApplicationColoursMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloption> tbloptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloption> tbloptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloption> tbloptions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloption> tbloptions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloption> tbloptions4 { get; set; }
    }
}
