//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcoreToBeDeleted
    {
        public int id { get; set; }
        public string version { get; set; }
        public string domain { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public string tax { get; set; }
        public string currency { get; set; }
        public Nullable<int> autobackup { get; set; }
        public Nullable<int> cronjob { get; set; }
        public Nullable<int> last_cronjob { get; set; }
        public Nullable<int> last_autobackup { get; set; }
        public string invoice_terms { get; set; }
        public Nullable<int> company_reference { get; set; }
        public Nullable<int> project_reference { get; set; }
        public Nullable<int> invoice_reference { get; set; }
        public Nullable<int> subscription_reference { get; set; }
        public Nullable<int> ticket_reference { get; set; }
        public string date_format { get; set; }
        public string date_time_format { get; set; }
        public string invoice_mail_subject { get; set; }
        public string pw_reset_mail_subject { get; set; }
        public string pw_reset_link_mail_subject { get; set; }
        public string credentials_mail_subject { get; set; }
        public string notification_mail_subject { get; set; }
        public string language { get; set; }
        public string invoice_address { get; set; }
        public string invoice_city { get; set; }
        public string invoice_contact { get; set; }
        public string invoice_tel { get; set; }
        public string subscription_mail_subject { get; set; }
        public string logo { get; set; }
        public string template { get; set; }
        public string paypal { get; set; }
        public string paypal_currency { get; set; }
        public string paypal_account { get; set; }
        public string invoice_logo { get; set; }
        public string pc { get; set; }
        public string vat { get; set; }
        public string ticket_email { get; set; }
        public Nullable<int> ticket_default_owner { get; set; }
        public Nullable<int> ticket_default_queue { get; set; }
        public Nullable<int> ticket_default_type { get; set; }
        public string ticket_default_status { get; set; }
        public string ticket_config_host { get; set; }
        public string ticket_config_login { get; set; }
        public string ticket_config_pass { get; set; }
        public string ticket_config_port { get; set; }
        public string ticket_config_ssl { get; set; }
        public string ticket_config_email { get; set; }
        public string ticket_config_flags { get; set; }
        public string ticket_config_search { get; set; }
        public Nullable<int> ticket_config_timestamp { get; set; }
        public string ticket_config_mailbox { get; set; }
        public Nullable<int> ticket_config_delete { get; set; }
        public Nullable<int> ticket_config_active { get; set; }
        public Nullable<int> ticket_config_imap { get; set; }
    }
}
