//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblclientsToBeDeleted
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string userpic { get; set; }
        public string city { get; set; }
        public string password { get; set; }
        public Nullable<int> inactive { get; set; }
        public string access { get; set; }
        public string last_active { get; set; }
        public string last_login { get; set; }
    }
}
