//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompaniesToBeDeleted
    {
        public int id { get; set; }
        public int reference { get; set; }
        public string name { get; set; }
        public string client_id { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string city { get; set; }
        public Nullable<int> inactive { get; set; }
        public string website { get; set; }
        public string country { get; set; }
        public string vat { get; set; }
        public string note { get; set; }
    }
}
