//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldecoration
    {
        public int id { get; set; }
        public string name { get; set; }
        public int sort { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DecDate { get; set; }
        public string Type { get; set; }
        public string Garment { get; set; }
        public string Position { get; set; }
        public string Measurement { get; set; }
        public Nullable<int> Widthsize { get; set; }
        public Nullable<int> Lengthsize { get; set; }
        public string Designer { get; set; }
        public string AcctMgr { get; set; }
        public string DecStatus { get; set; }
        public string Invoiced { get; set; }
        public string DecNotes { get; set; }
        public string Image { get; set; }
    }
}
