//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDraftQuoteItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDraftQuoteItem()
        {
            this.tblDraftOrderItems = new HashSet<tblDraftOrderItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> Colour_Id { get; set; }
        public Nullable<int> Size_Id { get; set; }
        public string Size { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Quotes_Id { get; set; }
        public Nullable<decimal> Print_Price { get; set; }
        public Nullable<decimal> Totalprice { get; set; }
        public Nullable<int> Tshirt_Price { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<int> UserItemId { get; set; }
    
        public virtual tblDraftQuote tblDraftQuote { get; set; }
        public virtual tbluser tbluser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDraftOrderItem> tblDraftOrderItems { get; set; }
        public virtual tblUserItem tblUserItem { get; set; }
    }
}
