//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInquiry
    {
        public int InquiryId { get; set; }
        public Nullable<int> OpportunityId { get; set; }
        public string ItemColours { get; set; }
        public string PrefBrandsAndStyle { get; set; }
        public string GeneralNotes { get; set; }
        public string FrontPrintArt { get; set; }
        public string FrontPrintNotes { get; set; }
        public string BackPrintArt { get; set; }
        public string BackPrintNotes { get; set; }
        public string LeftPrintArt { get; set; }
        public string LEftPrintNotes { get; set; }
        public string RighPrintArt { get; set; }
        public string RightPrintNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tblOpportunity tblOpportunity { get; set; }
    }
}
