//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoicesToBeDeleted
    {
        public int id { get; set; }
        public Nullable<int> reference { get; set; }
        public int company_id { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public string issue_date { get; set; }
        public string due_date { get; set; }
        public string sent_date { get; set; }
        public string paid_date { get; set; }
        public string terms { get; set; }
        public string discount { get; set; }
        public string subscription_id { get; set; }
    }
}
