//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobCopy
    {
        public int id { get; set; }
        public int id_contact { get; set; }
        public int id_option { get; set; }
        public System.DateTime create_date { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> required_date { get; set; }
        public int ordered { get; set; }
        public string reason { get; set; }
        public Nullable<int> repeat_job { get; set; }
        public Nullable<int> send_quote { get; set; }
        public Nullable<decimal> job_value { get; set; }
        public string job_department { get; set; }
        public string quantity { get; set; }
    }
}
