//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkanban
    {
        public int KanbanId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> OppId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> MachineNo { get; set; }
        public Nullable<int> Priority { get; set; }
        public string KanbanStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbldepartment tbldepartment { get; set; }
        public virtual tblOpportunity tblOpportunity { get; set; }
    }
}
