//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmessagesToBeDeleted
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> media_id { get; set; }
        public string from { get; set; }
        public string text { get; set; }
        public string datetime { get; set; }
    }
}
