//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOptionProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOptionProperty()
        {
            this.tblUserItems = new HashSet<tblUserItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> OptionCodeId { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string FrontImage { get; set; }
        public string BackImage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblColor tblColor { get; set; }
        public virtual tblOptionCode tblOptionCode { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual tbluser tbluser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserItem> tblUserItems { get; set; }
    }
}
