//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloption
    {
        public int id { get; set; }
        public int quantity { get; set; }
        public string code { get; set; }
        public int band_id { get; set; }
        public int item_id { get; set; }
        public string colour { get; set; }
        public string comment { get; set; }
        public string private_comment { get; set; }
        public Nullable<int> front_decoration { get; set; }
        public Nullable<int> back_decoration { get; set; }
        public Nullable<int> left_decoration { get; set; }
        public Nullable<int> right_decoration { get; set; }
        public Nullable<int> extra_decoration { get; set; }
        public Nullable<double> uni_price { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<bool> include_job { get; set; }
        public string job_id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> OpportunityId { get; set; }
        public string SizeGrid { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public string InitialSizes { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public string Front_decDesign { get; set; }
        public string Back_decDesign { get; set; }
        public string Left_decDesign { get; set; }
        public string Right_decDesign { get; set; }
        public string Extra_decDesign { get; set; }
        public string Front_decQuantity { get; set; }
        public string Back_decQuantity { get; set; }
        public string Left_decQuantity { get; set; }
        public string Right_decQuantity { get; set; }
        public string Extra_decQuantity { get; set; }
        public string Declined { get; set; }
        public string Service { get; set; }
        public Nullable<decimal> Front_decCost { get; set; }
        public Nullable<decimal> Back_decCost { get; set; }
        public Nullable<decimal> Left_decCost { get; set; }
        public Nullable<decimal> Right_decCost { get; set; }
        public Nullable<decimal> Extra_decCost { get; set; }
        public string OptionStage { get; set; }
        public Nullable<int> oldFront_decoration { get; set; }
        public Nullable<int> oldBack_decoration { get; set; }
        public Nullable<int> oldLeft_decoration { get; set; }
        public Nullable<int> oldRight_decoration { get; set; }
        public Nullable<int> oldExtra_decoration { get; set; }
        public Nullable<decimal> UnitInclGST { get; set; }
        public Nullable<decimal> ExtExGST { get; set; }
        public Nullable<decimal> ExtInclGST { get; set; }
        public string SizesPacked { get; set; }
        public Nullable<bool> ProofSent { get; set; }
        public Nullable<System.DateTime> ProofMailSent { get; set; }
        public Nullable<int> ProofVerion { get; set; }
        public string PaidBy { get; set; }
    
        public virtual TblApplication TblApplication { get; set; }
        public virtual TblApplication TblApplication1 { get; set; }
        public virtual TblApplication TblApplication2 { get; set; }
        public virtual TblApplication TblApplication3 { get; set; }
        public virtual TblApplication TblApplication4 { get; set; }
        public virtual tblband tblband { get; set; }
        public virtual tblitem tblitem { get; set; }
        public virtual tblOpportunity tblOpportunity { get; set; }
    }
}
