//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrderDetail()
        {
            this.OrderAddresses = new HashSet<OrderAddress>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserItemId { get; set; }
        public Nullable<int> createdBY { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    
        public virtual tbluser tbluser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAddress> OrderAddresses { get; set; }
        public virtual tblUserItem tblUserItem { get; set; }
    }
}
