//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOptionCode
    {
        public int id { get; set; }
        public string Code { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status { get; set; }
    
        public virtual tblband tblband { get; set; }
        public virtual tblitem tblitem { get; set; }
    }
}
