//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PmtId { get; set; }
        public Nullable<int> OpportunityId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<decimal> OppBalance { get; set; }
        public Nullable<System.DateTime> PmtDate { get; set; }
        public Nullable<decimal> AmtReceived { get; set; }
        public string PmtMethod { get; set; }
        public string MemoDesc { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DepositAccountNo { get; set; }
        public string DepositAccountName { get; set; }
    
        public virtual tblOrganisation tblOrganisation { get; set; }
        public virtual tblOpportunity tblOpportunity { get; set; }
    }
}
