//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprojectsToBeDeleted
    {
        public int id { get; set; }
        public Nullable<int> reference { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public Nullable<decimal> progress { get; set; }
        public string phases { get; set; }
        public Nullable<int> tracking { get; set; }
        public Nullable<int> time_spent { get; set; }
        public Nullable<int> datetime { get; set; }
        public Nullable<int> sticky { get; set; }
        public string category { get; set; }
        public int company_id { get; set; }
        public string note { get; set; }
        public Nullable<int> progress_calc { get; set; }
    }
}
