//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseDetail
    {
        public int PurchaseDetailId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public int quantity { get; set; }
        public string code { get; set; }
        public int band_id { get; set; }
        public int item_id { get; set; }
        public string colour { get; set; }
        public string comment { get; set; }
        public Nullable<double> uni_price { get; set; }
        public Nullable<bool> include_job { get; set; }
        public string job_id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> OpportunityId { get; set; }
        public string SizeGrid { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string InitialSizes { get; set; }
        public Nullable<decimal> UnitInclGST { get; set; }
        public Nullable<decimal> ExtExGST { get; set; }
        public Nullable<decimal> ExtInclGST { get; set; }
        public string ItemNotes { get; set; }
    
        public virtual tblband tblband { get; set; }
        public virtual tblitem tblitem { get; set; }
        public virtual tblOpportunity tblOpportunity { get; set; }
    }
}
