//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproject_has_tasksToBeDeleted
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string name { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> @public { get; set; }
    }
}
