//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Size_Id { get; set; }
        public Nullable<int> Colour_Id { get; set; }
    
        public virtual tblApplicationProcess tblApplicationProcess { get; set; }
        public virtual tblSizeMaster tblSizeMaster { get; set; }
        public virtual tblPrintColor tblPrintColor { get; set; }
    }
}
