//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsubscriptionsToBeDeleted
    {
        public int id { get; set; }
        public string reference { get; set; }
        public Nullable<int> company_id { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public string issue_date { get; set; }
        public string end_date { get; set; }
        public string frequency { get; set; }
        public string next_payment { get; set; }
        public string terms { get; set; }
        public string discount { get; set; }
        public string subscribed { get; set; }
    }
}
