//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticket_has_articlesToBeDeleted
    {
        public long id { get; set; }
        public Nullable<int> ticket_id { get; set; }
        public string from { get; set; }
        public string reply_to { get; set; }
        public string to { get; set; }
        public string cc { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string datetime { get; set; }
        public Nullable<int> @internal { get; set; }
    }
}
