//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltempJobCleanData
    {
        public int JCId { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> Newid_Contact { get; set; }
        public string DeleteFlag { get; set; }
    }
}
