//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticketsToBeDeleted
    {
        public long id { get; set; }
        public string from { get; set; }
        public string reference { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> @lock { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string status { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> escalation_time { get; set; }
        public string priority { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<int> queue_id { get; set; }
        public Nullable<int> updated { get; set; }
    }
}
