//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbluser()
        {
            this.tblcontacts = new HashSet<tblcontact>();
            this.tblOrganisations = new HashSet<tblOrganisation>();
            this.TblApplications = new HashSet<TblApplication>();
            this.tblColors = new HashSet<tblColor>();
            this.tblFabrics = new HashSet<tblFabric>();
            this.tblOptionProperties = new HashSet<tblOptionProperty>();
            this.tblOptionProperties1 = new HashSet<tblOptionProperty>();
            this.tblUserAddressMappings = new HashSet<tblUserAddressMapping>();
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
            this.tblDraftQuotes = new HashSet<tblDraftQuote>();
            this.tblDraftOrders = new HashSet<tblDraftOrder>();
            this.tblDraftQuoteItems = new HashSet<tblDraftQuoteItem>();
            this.tblUserLogoes = new HashSet<tblUserLogo>();
            this.tblUserItems = new HashSet<tblUserItem>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string hashed_password { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string userpic { get; set; }
        public string title { get; set; }
        public string access { get; set; }
        public string last_active { get; set; }
        public string last_login { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsProfileCompleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcontact> tblcontacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganisation> tblOrganisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblApplication> TblApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblColor> tblColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFabric> tblFabrics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOptionProperty> tblOptionProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOptionProperty> tblOptionProperties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserAddressMapping> tblUserAddressMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDraftQuote> tblDraftQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDraftOrder> tblDraftOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDraftQuoteItem> tblDraftQuoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLogo> tblUserLogoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserItem> tblUserItems { get; set; }
    }
}
