//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_tblOpportunity
    {
        public int OpportunityId { get; set; }
        public Nullable<System.DateTime> OppDate { get; set; }
        public string OppName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Source { get; set; }
        public string OppNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Compaign { get; set; }
        public string Stage { get; set; }
        public string QuoteNotes { get; set; }
        public string OrderNotes { get; set; }
        public string JobNotes { get; set; }
        public string PackingNotes { get; set; }
        public string InvoicingNotes { get; set; }
        public string ShippingNotes { get; set; }
        public string CompleteNotes { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> DepositReqDate { get; set; }
        public string RepeatJob { get; set; }
        public Nullable<int> RepeatJobId { get; set; }
        public string Shipping { get; set; }
        public string Price { get; set; }
        public string Service { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ProdLine { get; set; }
        public Nullable<System.DateTime> DispDate { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public Nullable<System.DateTime> JobDate { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public Nullable<System.DateTime> InvoicingDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> StockInDate { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> ArtOrderedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> ArtReadyDate { get; set; }
        public Nullable<System.DateTime> StockOrderedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> Checkeddate { get; set; }
        public Nullable<System.DateTime> DecoratedDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Declined { get; set; }
        public string Lost { get; set; }
        public string Cancelled { get; set; }
        public string ShippingTo { get; set; }
        public string job_department { get; set; }
        public Nullable<int> OldJob_id { get; set; }
        public Nullable<double> OldJob_value { get; set; }
        public Nullable<bool> oldsend_quote { get; set; }
        public string oldQty_Range { get; set; }
        public string Oldmyob_ord { get; set; }
        public Nullable<bool> Olddigital_art { get; set; }
        public Nullable<bool> Oldbrief_to_artroom { get; set; }
        public Nullable<System.DateTime> Oldproof_to_client { get; set; }
        public Nullable<bool> oldstock_in { get; set; }
        public Nullable<bool> oldIn_production { get; set; }
        public Nullable<bool> old_packed { get; set; }
        public Nullable<bool> old_paid { get; set; }
        public string OldProd_notes { get; set; }
        public Nullable<bool> OldIs_active { get; set; }
        public Nullable<System.DateTime> Oldconv_date { get; set; }
        public Nullable<System.DateTime> Oldconv_date_bk { get; set; }
        public string OppThumbnail { get; set; }
        public string QuoteMail { get; set; }
        public Nullable<int> AcctManagerId { get; set; }
        public Nullable<decimal> GSTValue { get; set; }
        public Nullable<System.DateTime> QuoteMailDate { get; set; }
        public Nullable<System.DateTime> OrderMailDate { get; set; }
        public string Complete { get; set; }
        public Nullable<System.DateTime> OrderConfirmedDate { get; set; }
        public string PackedInSet1 { get; set; }
        public string PackedInSet2 { get; set; }
        public string ConsigNoteNo { get; set; }
        public string PacagingNotes { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.DateTime> ConfirmMailDate { get; set; }
        public Nullable<System.DateTime> InvoiceMailDate { get; set; }
        public string OutSourcerName { get; set; }
        public Nullable<System.DateTime> JobAcceptedDate { get; set; }
        public Nullable<System.DateTime> ProofCreatedDate { get; set; }
        public Nullable<System.DateTime> ProofSentdate { get; set; }
        public string DeliveryDate { get; set; }
        public string DisplayOpportunityId { get; set; }
        public string StageWiseNotes { get; set; }
        public Nullable<System.DateTime> StageWiseDate { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string email { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string Contactfullname { get; set; }
        public string EventName { get; set; }
        public string AccountManagerFirstName { get; set; }
        public string AccountManagerLastName { get; set; }
        public string AccountManagerFullName { get; set; }
        public string AccountManagerName { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public int Totalpayment { get; set; }
    }
}
