//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEN_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tblKanban
    {
        public int KanbanId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> OppId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> MachineNo { get; set; }
        public Nullable<int> Priority { get; set; }
        public string KanbanStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AccountManagerName { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string OppName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> ArtOrderedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> ArtReadyDate { get; set; }
        public Nullable<System.DateTime> StockOrderedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> Checkeddate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string OppThumbnail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string FrontPrint { get; set; }
        public string BackCount { get; set; }
        public string LeftCount { get; set; }
        public string RightCount { get; set; }
        public string ExtraCount { get; set; }
        public Nullable<System.DateTime> DecoratedDate { get; set; }
    }
}
